# 张量

Tensor（张量）类似于numpy的ndarray，但是可以在gpu上加速运算。

## 张量的创建

In [3]:
from __future__ import print_function
import torch


# 初始化一个空的指定维度的张量
# 空张量并不意味指着张量哪没有值，值会被随意填充
x = torch.empty(5, 3)
print(x)

tensor([[0.0000e+00, 1.0842e-19, 0.0000e+00],
        [1.0842e-19, 1.2612e-44, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00]])


In [ ]:
# 使用随机值创建一个指定维度的张量
# 随机值在0-1之间
x = torch.rand(5, 3)
print(x)

In [ ]:
# 创造一个由0填充的指定维度的张量
# 通过dtype关键字指定数据类型
# 数据类型是torch类型，非python本身类型
x = torch.zeros(5, 3, dtype=torch.long)
print(x)

In [6]:
# 当然最直接的张量创建是从多维数组（python列表）直接创建
# 列表中的不同number类型在创建过程中会被强制转换
# 张量中只能存在一种数据类型
import numpy as np

ndarray = np.zeros((5, 3))
x = torch.Tensor([5.3, 3])
y = torch.Tensor(ndarray)
print(x)
print(y)

tensor([5.3000, 3.0000])
tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])


In [21]:
# 可以根据已有的张量创建新的张量
# 除非主动声明新的参数，否则原始张量的参数将重用为新的张量
x = x.new_ones(5, 3, dtype=torch.int)
print(x)

x = torch.randn_like(x, dtype=torch.float)
print(x)

tensor([[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]], dtype=torch.int32)
tensor([[-0.8157, -0.4413, -0.6714],
        [-2.0948, -0.2688,  0.5878],
        [ 0.9025,  1.8613,  0.9745],
        [-0.8771, -1.7909,  0.1759],
        [ 0.0830, -0.8906,  2.1953]])


In [ ]:
# 通过张量对象的自身方法来获取张量的一些属性
# 如获取张量的形状
print(x.size())

## 张量的运算

+ **张量的一种运算有多种语法，下面以加法为例说明**

In [20]:
# 使用+运算符
y = torch.rand(5, 3)
print(x + y)

tensor([[ 1.0380, -0.1613,  0.0968],
        [-0.7205, -1.3461, -0.3562],
        [ 2.6907,  1.0537, -1.4699],
        [-0.7504,  0.9114, -0.9243],
        [ 0.6866, -0.4212,  0.8608]])


In [22]:
# 使用模块即的加法函数
print(torch.add(x, y))

tensor([[-0.1338,  0.1246,  0.2279],
        [-2.0436,  0.0202,  0.7113],
        [ 1.7398,  2.3485,  1.0245],
        [-0.4253, -1.7846,  0.2676],
        [ 0.1148, -0.3181,  2.8808]])


In [27]:
# 可以给出一个张量，作为限定输出格式的参数
result = torch.empty(5, 2, dtype=torch.double)
torch.add(x, y, out=result)
print(result)

tensor([[-0.1338,  0.1246,  0.2279],
        [-2.0436,  0.0202,  0.7113],
        [ 1.7398,  2.3485,  1.0245],
        [-0.4253, -1.7846,  0.2676],
        [ 0.1148, -0.3181,  2.8808]], dtype=torch.float64)


In [28]:
# 使用张量的内置方法实现原位操作
# 任何一个原位操作改变张量的方法后都固定一个_，例如x.copy_(y)、x.t_()将更改x
y.add_(x)
print(y)

tensor([[-0.1338,  0.1246,  0.2279],
        [-2.0436,  0.0202,  0.7113],
        [ 1.7398,  2.3485,  1.0245],
        [-0.4253, -1.7846,  0.2676],
        [ 0.1148, -0.3181,  2.8808]])


+ **张量可以像标准的numpy一样进行索引操作**

In [29]:
print(x[:, 1])

tensor([-0.4413, -0.2688,  1.8613, -1.7909, -0.8906])


In [32]:
# 可以通过view方法改变张量的形状
# 该方法不是原位操作，有返回值
x = torch.randn(4, 4)
y = x.view(16)
z = x.view(-1, 8)  # 参数-1表示由其它维度参数推测该维度应该是多少
print(x)
print(y)
print(z)

tensor([[-0.7122,  0.4794,  0.8359,  1.3936],
        [ 0.4523,  0.3215,  0.8064, -1.0482],
        [ 0.9320, -1.5026, -1.9578,  0.2176],
        [-0.6940, -0.4341, -0.1991,  0.9731]])
tensor([-0.7122,  0.4794,  0.8359,  1.3936,  0.4523,  0.3215,  0.8064, -1.0482,
         0.9320, -1.5026, -1.9578,  0.2176, -0.6940, -0.4341, -0.1991,  0.9731])
tensor([[-0.7122,  0.4794,  0.8359,  1.3936,  0.4523,  0.3215,  0.8064, -1.0482],
        [ 0.9320, -1.5026, -1.9578,  0.2176, -0.6940, -0.4341, -0.1991,  0.9731]])


+ **当张量只包含单值时，可以使用item()方法来获取相应的python值**

In [33]:
x = torch.randn(1)
print(x)
print(x.item())

tensor([1.3032])
1.3032257556915283


## 张量支持超过100种运算操作，包括转置，索引，切片，数学运算，线性代数，随机数等，具体访问[这里](https://pytorch.org/docs/stable/torch.html)。

# 桥接NumPy

将一个Torch张量转换为一个NumPy数组是轻而易举的事情，反之亦然。

**Torch张量和NumPy数组将共享它们的底层内存位置，因此当一个改变时,另外也会改变。**

In [5]:
a = torch.ones(5)
print(a)

tensor([1., 1., 1., 1., 1.])


In [11]:
modulvars = dir()
if ('numpy' in modulvars) or ('np' not in modulvars):
    import numpy as np

b = a.numpy()
print(b)

[1. 1. 1. 1. 1.]


In [12]:
# 共享一块内存位置
# 其中一个改变数值后另一个也会体现
a.add_(1)
print(a)
print(b)

tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


## 将numpy数组转换为张量

In [15]:
modulvars = dir()
if ('numpy' in modulvars) or ('np' not in modulvars):
    import numpy as np

# 由numpy数组转换来的张量同样共享一块内存
a = np.ones(5)
b = torch.from_numpy(a)
# b = torch.Tensor(a)  # 这样新建张量对象，不会共享内存
np.add(a, 1, out=a)
print(a)
print(b)

[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


## CUDA上的张量

+ **张量可以使用.to方法移动到任何设备(device)上**

In [17]:
# 当GPU可用时，可以运行以下代码
# 使用torch.device来将张量移入和移除GPU
if torch.cuda.is_available():
    device = torch.device("cuda")            # 创建一个CUDA对象
    y = torch.ones_like(x, device=device)    # 直接在GPU上创建张量
    x = x.to(device)                         # 或者使用.to("cuda")语法
    z = x + y
    print(z)
    print(z.to("cpu", torch.double))         # .to方法也能在移动时改变数据类型